name: Django Backend CI

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd kb_backend
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Check Formatting
        run: |
          pip install flake8
          flake8
